# Generated by Django 2.2.10 on 2021-03-31 11:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date(2021, 3, 31), editable=False)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuizParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Question_set')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Question_type')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_option', models.CharField(blank=True, max_length=500, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Answer_option')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
